version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydbbi
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/mydbbi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8089:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data_test:
    driver: local
